version: '2'
services:
  db:
    image: mongo
    ports:
    - 'localhost:27017:27017'
  app:
    build: .
    command: ['/bin/bash', './wait-for-it.sh', 'db:27017', '--strict', '--', 'node', './dist/app.js']
    depends_on:
      - db
    ports:
      - '8000:8000'
    environment:
      - MONGODB_PATH=mongodb://db:27017/oink
      - PORT=8000
    volumes:
      - ./dist:/app/dist:Z
      - ./templates:/app/templates:Z